### ISSUE TITLE
Handling of optional fields

### ISSUE THREAD

**Issue by sebastinas** [Kixunil/rfc822-like#1]
Consider the following example:
```rust
use serde::Deserialize;

#[derive(Deserialize, Eq, PartialEq, Debug)]
#[serde(rename_all = "PascalCase")]
struct Package {
    package: String,
    source: Option<String>,
}

fn main() {
    let data = "Package: foo
Source: bar

Package: baz
";
    let packages: Vec<Package> = rfc822_like::from_str(data).unwrap();
    assert_eq!(packages[0].package, "foo");
    assert_eq!(packages[0].source, Some("bar".to_string()));
    assert_eq!(packages[1].package, "baz");
    assert_eq!(packages[1].source, None);
}
```
It fails with `Error(Custom("invalid type: string \"bar\", expected option"))`. Given that many of the fields in `debian/control` or other files using Debian's variant of RFC822 are optional, it would be nice to support handling of such fields.

**Comment by Kixunil** [comment]
Thanks for reporting! I agree and because of the importance I consider this being a bug. Hopefully I will be able to find some time for it in the future.

OT: happy to see a Debian developer with interest in this! :)

**Comment by Kixunil** [comment]
Please check version 0.1.1 and let me know if there's any other problem.

**Comment by sebastinas** [comment]
Thanks! That works for me.
